### ISSUE TITLE
Port changed from 444 to 1080

### ISSUE THREAD

**Issue by delete** [erickponce/sonicwall-logon#2]
The default port have changed from 444 to 1080, can I send a PR?

https://github.com/erickponce/sonicwall-logon/blob/master/auth.conf#L7

**Comment by erickponce** [comment]
That's strange, i can still authenticate with port 444.

**Comment by delete** [comment]
I did a nmap and yes, both are opened.

I realized that I can only access the 444 with `https` and 1080 with `http`.
It seems, for some reason, the service was trying to connect using `http` only.

**Comment by erickponce** [comment]
Ok, we can check the code to enforce https, or use a protocol/port based on configuration.
